---
title: "OpenBugs"
author: "Michael Andreae"
date: "December 11, 2015"
output: pdf_document
---

```{r, global_options, echo=FALSE}
suppressWarnings(library(knitr))
# set options
opts_chunk$set(fig.width=6, fig.height=4, fig.path='Figs/',
               echo=FALSE, warning=FALSE, message=FALSE)
eval_everything=FALSE
```


We are trying to repeat the analysis by Dr. Johnson's for the ICBG evidency synthesis for ACE 151

```{r}
library(R2OpenBUGS)
```

# OpenBugs Example

We followed the [Tutorial](<http://www.r-tutor.com/bayesian-statistics/openbugs)

```{r, Example, eval=eval_everything, echo=eval_everything}

model <- function() { 
    # Prior 
    p ~ dbeta(1, 1) 
 
    # Likelihood 
    y ~ dbin(p, N) 
}

# To transfer the model to OpenBUGS, we load the R2OpenBUGS extension
# and write the model to a temporary location using the method
# write.model. We denote the model file location by model.file.

library(R2OpenBUGS) 
model.file <- file.path(tempdir(), 
                        "model.txt") 
write.model(model, model.file)

# Problem
# The data set survey contains sample smoker statistics among
# university students. Denote the proportion of smokers in the general
# student population by p. With uniform prior, find the mean and
# standard deviation of the posterior of p using OpenBUGS.

# Then we have to decide data parameters of the BUGS model. We find
# that there are 236 students in the survey, and 47 of them smoke,
# which we denote by N and y respectively.

library(MASS) 
tbl <- table(survey$Smoke) 
N <- as.numeric(sum(tbl)); N 

y <- N - as.numeric(tbl["Never"]); y 

# We then identify data variables in a list called data.

data <- list("N", "y")

# And we identify the variable p to be monitored in a vector called
# params.

params <- c("p")

# Lastly, we need to select some initial parameters for the simulation.
# A rule of thumb is to choose values as close to the expected result
# as possible. In this case, we initialize p to be 0.5. Notice how we
# wrap the initial values inside a list that is to be returned by a
# function.

inits <- function() { list(p=0.5) }

# Then we invoke OpenBUGS with the namesake method bugs and save the
# result in a variable out. We select 10,000 iterations per simulation
# chain.

out <- bugs(data, inits, params,  model.file, n.iter=10000)
out$summary


# Better to invoke the CODA option to get mcmc.list as output.

out <- bugs(data, inits, params, model.file, codaPkg=TRUE,
            n.iter=10000) 
out.coda <- read.bugs(out) 

# Analyse using shinystan

library(shinystan)
library(coda)

# After verification that the opject is now a mcmc.list
# convert to shinstan object and call shinystan

is.mcmc.list(out.coda)
out.shiny <- as.shinystan(out.coda)
#launch_shinystan(out.shiny)
```

# Repeating Dr. Johnson ICBG Analysis

```{r, Johnson, eval=TRUE, echo=TRUE}

rm(list=ls())

# Model with old data

model <- function() { 

	##############################
	# Blumenthal                                      #
	##############################
	for(i in 0:3){
		logL[1,i+1] <- i*log(p[1,1]) +(18-i)*log(1-p[1,1]) - logfact(i) - logfact(18-i) + logfact(18)
		L[1,i+1] <- exp(logL[1,i+1]) 
		p1[i+1] <- L[1,i+1]/sum(L[1,1:4])
	}
	for(i in 16:18){
		logL[2,i-15] <- i*log(p[1,2]) + (18-i)*log(1-p[1,2]) - logfact(i) - logfact(18-i)+logfact(18)
		L[2,i-15] <- exp(logL[2,i-15])
		p2[i-15] <- L[2,i-15]/sum(L[2,1:3]) 
	}
	for(i in 1:2){
		d[i] <- 1
		d[i] ~ dbern(LogLike[i])
		LogLike[i] <- mean(L[i,1:(r[i])])
	}
	######################################
	
	##################################
	# Other Studies                                         #
	##################################
	for(i in 1:3){
		for(j in 1:2){
			x[i,j] ~ dbin(p[i+1,j],N[i,j])
		}
	}
	####################################
	
	####################################
	# Priors                                                          #
	####################################
	for(i in 1:4){
		for(j in 1:2){
			logit(p[i,j]) <- gamma[i,j]
		}
		gamma[i,1:2] ~ dmnorm(gamma[5,1:2],Tau[1:2,1:2])
		#gamma[i,1] ~ dnorm(gamma[5,1],
		or[i] <- exp(gamma[i,1]-gamma[i,2])
	}
	gamma[5,1] ~ dnorm(0,0.001)
	gamma[5,2] ~ dnorm(0,0.001)
	or[5] <- exp(gamma[5,1]-gamma[5,2])
	logit(p[5,1]) <- gamma[5,1]
	logit(p[5,2]) <- gamma[5,2]
	nnt <- 1/(p[5,2] - p[5,1])
	Sigma[1] ~  dt(0,3,1)#T(0,)
	Sigma[2] ~ dt(0,3,1)#T(0,)
	rho ~ dunif(-1,1)
	Sigma[3] <- rho*sqrt(Sigma[1]*Sigma[2])
	det <- Sigma[1]*Sigma[2] - Sigma[3] * Sigma[3]
	Tau[1,1] <- Sigma[2]/det
	Tau[2,2] <- Sigma[1]/det
	Tau[1,2] <- -Sigma[3]/det
	Tau[2,1] <- Tau[1,2]
}


# To transfer the model to OpenBUGS, we load the R2OpenBUGS extension
# and write the model to a temporary location using the method
# write.model. We denote the model file location by model.file.

library(R2OpenBUGS) 
model.file <- file.path(tempdir(), 
                        "model.txt") 
write.model(model, model.file)

# We then identify data variables in a list called data.

data = list (r=c(4,3),
             N=structure(.Data=c(30,15,11,11,9,11),.Dim=c(3,2)),
             x=structure(.Data=c(2,5,2,6,0,7),.Dim=c(3,2)),
             Sigma=c(1,1,NA),rho=0)

# Gundes, Brull, Singh #

# And we identify the variable p to be monitored in a vector called
# params.

params <- c("or", "nnt", "p")

# Lastly, we may select some initial parameters for the simulation.
# A rule of thumb is to choose values as close to the expected result
# as possible. In this case, we initialize p to be 0.5. Notice how we
# wrap the initial values inside a list that is to be returned by a
# function.

#inits <- function() { list(p=0.5) }

# Then we invoke OpenBUGS with the namesake method bugs and save the
# result in a variable out. We select 10,000 iterations per simulation
# chain.

out <- bugs(data, inits = NULL, params,  model.file, n.iter=10000)
out$summary


# Better to invoke the CODA option to get mcmc.list as output.

out <- bugs(data, inits = NULL, params, model.file, codaPkg=TRUE,
            n.iter=10000) 
out.coda <- read.bugs(out) 

# Analyse using shinystan

library(shinystan)
library(coda)

# After verification that the opject is now a mcmc.list
# convert to shinstan object and call shinystan

is.mcmc.list(out.coda)
out.shiny <- as.shinystan(out.coda)
# launch_shinystan(out.shiny)
```
